(function () {
  'use strict';

  angular
    .module('webAppNameWebApp')
    .constant('labels', {

      //welcome
      welcome: 'Welcome',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      signOut: 'Sign Out',
      rememberMe: 'Remember Me',
      recoverPassword: 'Recover password',
      recoverPasswordButton: 'Recover',
      passwordRecovery: 'Password Recovery',
      parachut: 'Parachut',
      version: 'Version',
      resetPassword: 'Change',
      email: 'Email',
      enterEmail: 'Please enter your e-mail address.',
      enterNewPassword: 'Please enter your new password.',
      haveVerifyEmail: 'You have to verify your email before first signing it. The verification link was sent to your email.',
      password: 'Password',
      firstName: 'First Name',
      lastName: 'Last Name',
      agreeTerms: 'By signing up, I agree to Parachut\'s',
      termsService: 'Terms of Service',
      leaseAgreement: 'Lease Agreement',
      and: 'and',
      receiveNews: 'I\'d like to receive awesome news and inspiration',

      //footer
      copyright: 'Copyright years Parachut LLC.',
      rightsReserved: 'All Rights Reserved.',

      //wizard-start
      congratulations: 'Congratulations!',
      congratulationsText: 'You are one step closer to experiencing all Parachut has to offer. To help us with the right product selection, it is important for us to learn about your habits and preferences.',
      start: 'Start',
      welcomeBack: 'Welcome Back!',
      welcomeBackText: 'We need to know you better to send your first `Chute Drop. Please complete your profile and we will start working on its contents.',
      complete: 'Complete',

      //photographerProfile
      photographerProfile: 'Profile',
      mySkillLevel: 'My Skill Level',
      beginner: 'Beginner',
      hobbyist: 'Hobbyist',
      professional: 'Pro-Quality',
      myPoison: 'My Poison',
      photo: 'Photo',
      video: 'video',
      myMethod: 'My Method',
      digital: 'Digital',
      analog: 'Analog',
      both: 'both',
      whatIShoot: 'What I Shoot',
      whatIShootTitle: 'Check all that apply',
      whatIShootSecondTitle: 'If Portrait, What Kind?',
      //shoots
      portrait: 'Portrait',
      editorial: 'Editorial',
      food: 'Food',
      animalWildlife: 'Animal/Wildlife',
      architecture: 'Architecture',
      underwater: 'Underwater',
      documentary: 'Documentary',
      timelapse: 'Timelapse',
      weddings: 'Weddings',
      travel: 'Travel',
      product: 'Product',
      nature: 'Nature',
      macro: 'Macro',
      sportsActions: 'Sports/Actions',
      events: 'Events',
      landscapes: 'Landscapes',
      childrenFamily: 'Children/Family',
      boudoir: 'Boudoir',
      fashion: 'Fashion',
      street: 'Street',
      fineArt: 'Fine Art',
      headShots: 'HeadShots',
      highschoolSeniors: 'Highschool Seniors',
      newborns: 'Newborns',

      //wish-list myBag
      wishList: 'Wish List',
      emptyWishList: 'You have not added your wishes',
      emptyWishListDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quisnostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      surpriseMe: 'Surprise Me',
      surprise: 'Surprise',
      inYourBag: 'In Your Bag',
      whatInYourBag: 'What`s In Your Bag',
      emptyMyBag: 'You have not added your bag',
      emptyMyBagDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quisnostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      all: 'All',
      cameras: 'Cameras',
      lenses: 'Lenses',
      lightning: 'Lightning & ACCESSORIES',
      speciality: 'Speciality & Video Items',
      add: 'Add',
      show: 'Show',

      //suggest-item
      suggestItem: 'Suggest an Item',
      name: 'Name',

      //invite-friend
      inviteFriend: 'Invite a Friend',
      invite: 'Invite',

      //reserve-your-spot
      //membership
      reserveYourSpot: 'Reserve Your Spot',
      membershipType: 'Membership Type',
      membership: 'Membership',
      membershipTitle: 'Lerem Ipsum Title',
      membershipText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quisnostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      membershipPayment: '$149/month',
      basic: 'Basic',
      changeMembership: 'Change membership',
      changeMembershipRequest: 'You requested to change memberhip on ',
      pause: 'i don\'t want to receive anything yet',
      membershipPausePayment: 'Pause',
      selectMembership: 'Select Membership Plan',
      selectMembershipDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quisnostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      membershipAgreement: ' I agree to the Parachut Reservation & Payment terms and Conditions.',
      membershipReviewInformational: 'You will not be billed today. You are only reserving your spot. You will be notified before your order is processed with the ability to cancel your reservation.',
      membershipMotivationText: 'Membership Motivation Text',
      requestPaused: 'You requested to cancel your membership',
      //insurance
      protectionPlan: 'Protection Plan',
      protectionTitle: 'Lerem Ipsum Title',
      protectionText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quisnostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      eliteCoverage: 'Elite Coverage',
      noCoverage: 'I don`t want insurance',
      elitePayment: '$45/month',
      noPayment: 'No thanks',
      selectProtection: 'Select Protection Plan',
      selectProtectionDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quisnostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      insurance: 'Insurance',
      //personal-info
      personalInformation: 'Personal Information',
      personal: 'Personal',
      shippingAddress: 'Shipping Address',
      shippingAddressSignature: 'Signature required for delivery. No P.O. Boxes',
      phone: 'Phone',
      address: 'Address',
      city: 'City',
      state: 'State',
      zipCode: 'Zip Code',
      //billing-info
      billingInformation: 'Billing Information',
      creditCard: 'Credit Card Info',
      creditCardLink: 'Is my credit card information safe?',
      cardNumber: 'Card Number',
      cardName: 'Name On The Card',
      expirationMonth: 'Expiration Month',
      expirationYear: 'Expiration Year',
      cvv: 'CVV',
      sameAsShipping: 'Same as shipping address',
      differentAddress: 'Different Address',
      billingAddress: 'Billing Address',
      changeCard: 'Change card',
      newCreditCard: 'New Credit Card',
      //review
      reserve: 'Reserve',
      review: 'Review',
      shipping: 'Shipping',
      taxes: 'Taxes',
      total: 'Total',
      dueToday: 'Due Today',

      //buttons
      close: 'Close',
      submit: 'Submit',
      next: 'Next',
      save: 'Save',
      cancel: 'Cancel',
      update: 'Update',
      back: 'Back',
      done: 'Done',

      //chutDrop
      chutDrop: '\'Chut Drop',
      shippingLabel:'Shipping label',
      orderNumber:'Order Number',
      deliveryDate:'Delivery Date',
      tracking:'Tracking',
      status:'Status',
      return: 'Return',
      returnChutDrop: 'I\'m ready to return',
      returnInstructionTitle: 'Return Instruction',
      returnInstructionDescription: 'You can free return your \'chutDrop using \'return label\' from your package.\n\nAlternatively, you can get \'return label\' again by clicking \n\'SHIPPING LABEL\' button',
      yourRating: 'Your rating',
      rateItem :'Rate this item',
      requestBuy :'Request to buy',
      chutDropGatheringTitle: 'Hey! We are working on your \'Chut Drop',
      chutDropGatheringDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      chutDropPausedTitle: 'Paused',
      chutDropPausedDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      reviewTextPlaceholder: 'Tell us what you liked or didn\'t like',
      describeDamage: 'Describe the damage',
      describeSituation: 'Describe the situation',
      globalRating:'Global rating',
      rewrite:'Rewrite review',
      write:'Write review',
      sendAgain: 'I\'d like to receive this item again',

      contactUs: 'Contact Us',
      tour: 'Tour',
      accountInfo: 'Account Info',
      updated: 'Data has been saved.',
      yes: 'Yes',
      no: 'No'
    });
})();
